name: CI for DockerHub

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      APP_NAME: mnist-web-demo

    steps:
    - uses: actions/checkout@v1

    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: djkormo/$APP_NAME
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
